import { MousePointer2, Crop, Paintbrush, Eraser, Type, Square, Circle, Hand, ZoomIn, Pipette, Lasso, RectangleHorizontal, CircleEllipsis, Wand2, Pentagon, Minus, RectangleEllipsis, Hexagon, PaintBucket, Blend, Stamp, Sun, Flame, Droplets, PenTool } from 'lucide-react'

export default [
  { id: 'select', icon: MousePointer2, label: 'Select / Move', shortcut: 'V' },
  { id: 'crop', icon: Crop, label: 'Crop', shortcut: 'C' },
  { id: 'brush', icon: Paintbrush, label: 'Brush', shortcut: 'B' },
  { id: 'eraser', icon: Eraser, label: 'Eraser', shortcut: 'E' },
  { id: 'text', icon: Type, label: 'Text', shortcut: 'T' },
  { id: 'rect', icon: Square, label: 'Rectangle', shortcut: 'R' },
  { id: 'ellipse', icon: Circle, label: 'Ellipse', shortcut: 'O' },
  { id: 'hand', icon: Hand, label: 'Hand / Pan', shortcut: 'H' },
  { id: 'zoom', icon: ZoomIn, label: 'Zoom', shortcut: 'Z' },
  { id: 'eyedropper', icon: Pipette, label: 'Eyedropper', shortcut: 'I' },
  { id: 'lasso', icon: Lasso, label: 'Lasso', shortcut: 'L' },
  { id: 'marquee-rect',    icon: RectangleHorizontal, label: 'Rectangular Marquee', shortcut: 'M' },
  { id: 'marquee-ellipse', icon: CircleEllipsis,      label: 'Elliptical Marquee',  shortcut: 'M' },
  { id: 'magic-wand',      icon: Wand2,               label: 'Magic Wand',          shortcut: 'W' },
  { id: 'lasso-poly',      icon: Pentagon,            label: 'Polygonal Lasso',     shortcut: 'L' },
  { id: 'line',            icon: Minus,               label: 'Line',                shortcut: 'U' },
  { id: 'rounded-rect',    icon: RectangleEllipsis,   label: 'Rounded Rectangle',   shortcut: 'U' },
  { id: 'polygon',         icon: Hexagon,             label: 'Polygon',             shortcut: 'U' },
  { id: 'paint-bucket',    icon: PaintBucket,         label: 'Paint Bucket',        shortcut: 'G' },
  { id: 'gradient',        icon: Blend,               label: 'Gradient',            shortcut: 'G' },
  { id: 'clone-stamp',     icon: Stamp,               label: 'Clone Stamp',         shortcut: 'S' },
  { id: 'dodge',           icon: Sun,                 label: 'Dodge',               shortcut: 'O' },
  { id: 'burn',            icon: Flame,               label: 'Burn',                shortcut: 'O' },
  { id: 'blur-brush',      icon: Droplets,            label: 'Blur Brush',          shortcut: 'R' },
  { id: 'pen',             icon: PenTool,             label: 'Pen',                 shortcut: 'P' },
]
